utilisateurs_homepage:
    path:     /
    defaults: { _controller: UtilisateursBundle:Utilisateurs:index }
    
factures:
    pattern: /profile/factures
    defaults: { _controller: UtilisateursBundle:Utilisateurs:factures }
    
facturesPDF:
    pattern: /profile/factures/pdf/{id}
    defaults: { _controller: UtilisateursBundle:Utilisateurs:facturesPDF }

